#!/bin/sh

echo Using uglify-js 3.1.1
cp package.3.1.1 package.json
rm -rf node_modules
npm install
./UglifyAndRun

echo
echo Using uglify-js 3.3.5
cp package.3.3.5 package.json
rm -rf node_modules
npm install
./UglifyAndRun

echo
echo Using uglify-js latest 3.x.x
cp package.^3.1.1 package.json
rm -rf node_modules
npm install
./UglifyAndRun
